### ISSUE TITLE
Refresh timeout option

### ISSUE THREAD

**Issue by gajuro** [melpon/memoize#18]
Hello,

First, thank you for a valuable library here.

I would need a strategy option that will refresh the cache after a given timeout. Basically, the function call will wait for the execution only the first time, after that it will return the cached value.

```
defmemo slow_function, refresh_in: 10 * 1000 do
end
```

I doubt that I will be able to write a strategy myself, but still, can you give me some hints for this? 

Thanks again.

**Comment by melpon** [comment]
Use `:expires_in`.
