### ISSUE TITLE
Is there a way to invalidate cached functions based on one of multiple arguments?

### ISSUE THREAD

**Issue by puruzio** [melpon/memoize#25]
For example, in a memoized function that takes two arguments (e.g., current_user and selected_date), I'd like to invalidate all caches for the current_user regardless of selected_date.
Is there a way to do that?

```
 Memoize.invalidate(Search, :run, [current_user])
```

```
defmodule Search do
  use Memoize
  defmemo run(current_user, selected_date)  do
       convert(selected_date, current_user.timezone)
       search(current_user.id)
 end
end

Search.run(%{id: "1234", name: "John Doe", timezone: "America/Los_Angeles"}, ~D[2023-11-11])
```

**Comment by melpon** [comment]
I haven't tried it, so I'm not sure if it works, but couldn't you invalidate with `Memoize.Cache.invalidate({Search, :run, [current_user, :_]})`?

**Comment by puruzio** [comment]
That works! Thank you.
