### ISSUE TITLE
waiter_sleep_ms: 0

### ISSUE THREAD

**Issue by edescourtis** [melpon/memoize#5]
We see massive degradation in performance once `:max_waiters` is reached because `:waiter_sleep_ms` is set to `0` by default. The CPU is wasting time spinning instead of completing the computation (under some circumstances even hitting the expiry before the computation completes). The default should be some minimal sleep time like 50ms to avoid this issue or a minimum between a faction of `expires_in` or 50ms (whatever works out to be smaller).

**Comment by JosephHalter** [comment]
The default is now `200`, I don't think this issue is relevant anymore.
