### ISSUE TITLE
disable in test env

### ISSUE THREAD

**Issue by PhilWaldmann** [melpon/memoize#6]
Hi,

is there a way to disable memoize in parallel tests?

Thanks,
Philipp

**Comment by melpon** [comment]
Not implemented in memoize. However you can write below:

```elixir
if Mix.env() == :test do
  def func() do
    do_func()
  end
else
  defmemo func() do
    do_func()
  end
end

def do_func() do
  ...
end
```

**Comment by PhilWaldmann** [comment]
not the most elegant solution, but the easiest ;)

Thanks,
Philipp
